### ISSUE TITLE
node-opencv が原因で、本ノードをインストールできない場合が多々あります

### ISSUE THREAD

**Issue by satour** [zuhito/node-red-contrib-opencv#3]
https://github.com/peterbraden/node-opencv
が事実上、メンテナンスされていない状態であり、かつサポートされている環境も実際にインストールしてみるまでわからない、という作りになっています（サポートれていない環境だと npm installでエラーになります）。

その為、本ノードも実際どういうマシンならインストールできるのか、インストールを試してみないとわからない状態です。

これはひとえに node-opencv のせいであり、同じ問題に直面している方も多いようで、node-opencvには700を超える多数のforkがあります。いずれかに依存先を変更したほうがいいのかと思いました。

**Comment by zuhito** [comment]
As I wrote on README.md, this node supports only Ubuntu and Raspbian environments. In my PC, the node works correctly. If you want to expand supporting environments, I welcome your pull request.
